version: '3.8'

services:
  app:
    build: .
    image: ${FULL_IMAGE_NAME}
    container_name: motasu-api-${DEPLOY_ENV}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HOST_PORT}:4000"
    environment:
      - NODE_ENV=${DEPLOY_ENV}
      - JWT_SECRET=${JWT_SECRET}
      # - DATABASE_URL=${DATABASE_URL}